### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by perlindgren** [helgoboss/helgoboss-midi#1]
Hi Helgoboss

I came across your crate while looking to implement support for `usb-midi` in `no_std` context. Your crate looks great, and I think it could be very usable also for embedded applications. I tried to strip it from `std` dependencies, but there is no `core::error` (https://github.com/rust-lang/rust/pull/33149).

So what's your take on this? 

(There are some other crates for midi with `no_std` support, but none seems as elegant as yours.)

Best regards
  Per Lindgren

**Comment by helgoboss** [comment]
Hi Per, glad you stumbled upon this crate and find it useful :) I would be happy to make this usable in a `no_std` context. Is the lack of `core::error` the only blocker you ran into?

I'm open to alternatives concerning the error types. Do you have any idea how this is usually handled in `no_std` crates? I just followed the rigorously the Rust API Guidelines (I think [this](https://rust-lang.github.io/api-guidelines/interoperability.html#c-good-err) in particular), therefore the current code.

**Comment by perlindgren** [comment]
Hi
I made a PR. There were a few dependencies that needed attention, but I got it to compile.

The main difference is that the `newtype::new` cannot use `format!` (I left the original code there commented out).

Especially in a `no_std` environment, "assert -> panic" is a bit problematic, perhaps `new` could return an `Option` (or even a `Result`). In any case the error is not local to `new` but rather a usage fault (you are trying to construct an illegal type).

Later one could think of a `no_std` (or `std`) as a feature, if you think there are some limitations to the `no-default-features` restriction on `num_enum`.

To be fair, I never used the `core-error` crate before, maybe there are other (better) options.

The tests pass, so I think you should be able to merge it as is.

/Per

**Comment by helgoboss** [comment]
Amazing, thanks for the PR. Will look into it.
