### ISSUE TITLE
Make `ControllerNumber::new` const-fn

### ISSUE THREAD

**Issue by Boscop** [helgoboss/helgoboss-midi#7]
Would it be possible to make `ControllerNumber::new` const-fn?
I saw there are predefined constants but they don't make semantic sense when writing mappings for midi controllers where e.g. CC 0 is crossfader.

![image](https://user-images.githubusercontent.com/535593/114061459-c30f2c80-9896-11eb-8016-1982956cdd5e.png)

Btw, thanks for the `ControlChange14BitMessageScanner`, that's very useful for this device :)

**Comment by helgoboss** [comment]
You can use the unsafe `new_unchecked()` function. It's `const`. The other one can't be made `const` as far as I know because it contains an assertion.

**Comment by helgoboss** [comment]
Feel free to reopen if still relevant.
